
nucProdigalDir: "workflow/out/nucProdigalTranslation"
nucProdigalDirwHeader: "workflow/out/nucProdigalwHeader"
hitStrainF: "config/butyrate_hit_strains_all_pathways.txt"

# local (RC's compooter)

#strainGenomeDir: "/Users/rebeccachristensen/Desktop/Cremer_Lab_2022/cysteine_utilization_project/main/config/strain_genomes"
#prodigalEnv: "../../workflow/envs/prodigal_local.yml"

# local (Daisy's compooter)
strainGenomeDir: "referenceGeneFiles"
prodigalEnv: "workflow/envs/prodigal_local.yml"

# remote (RC's Sherlock)

#prodigalEnv: "../../workflow/envs/prodigal.yml"
#strainGenomeDir: "/home/groups/quacks/RC/propionate_project/main/config/strain_genomes"

indexDir: "workflow/out/index"

#readsDir: "/scratch/users/reb26/reads"
# readsDir: "workflow/out/scratch/reads"
readsDir: "../shared_config/out/scratch/reads"

#reads_file: "config/pract.txt"
reads_file: "../shared_config/sra_run_accessions_Nayfach.txt"

#bowtieOutput: "/scratch/users/reb26/bt_output"
bowtieOutput: "workflow/out/scratch/bt_output"

#bowtieOutputHits: "/scratch/users/reb26/bt_hits"
bowtieOutputHits: "workflow/out/scratch/bt_hits"

#sraRepo: "/scratch/users/reb26/prefetched"
# sraRepo: "workflow/out/scratch/prefetched"
sraRepo: "../shared_config/out/scratch/prefetched"

hitSummaries: "workflow/out/bt_hit_summaries"

#readCounts: "/scratch/users/reb26/readCounts"
readCounts: "workflow/out/readCounts"
